version: "3"
services:
    
    api:
        build: .
        depends_on:
            - postgres
        ports:
            # - <port on localhost>:<port on container>
            - 8000:8000
        volumes:
            - ./:/usr/src/app:ro
        command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
        # env_file:
        #     - ./.env
        environment:
            - DB_HOST=postgres
            - DB_PORT=5432
            - DB_PASSWORD=secret
            - DB_USER=postgres
            - DB_NAME=fastapi_db
            - SECRET_KEY=97ed2cf10dcb17fab6b20f3612560fcb8f7f4595a987440f95e4ccb8c8f940fa
            - ALGORITHM=HS256
            - ACCESS_TOKEN_EXPIRE_MINUTES=60


    postgres:
        image: postgres
        environment:
            - POSTGRES_PASSWORD=secret
            - POSTGRES_DB=fastapi_db

        volumes:
            - postgres-db:/var/lib/postgresql/data

volumes:
    postgres-db:
